// Generated by `make brands` from data/brands/ - DO NOT EDIT.
// One entry per producer directory: who made the brand, the class its
// stylesheet is scoped to, and the manifest the app bar reads.

import type { BrandManifest, BrandProducer } from '../../../brand';

export interface BrandBuild {
  brand: string;
  producerId: string;
  producer: BrandProducer;
  model: string;
  date: string;
  scope: string;
  manifest: BrandManifest;
}

export const BRAND_BUILDS: readonly BrandBuild[] = [
  {
    brand: 'mthds',
    producerId: 'pipelex-method--claude-4.8-opus',
    producer: 'pipelex-method',
    model: 'claude-4.8-opus',
    date: '2026-09-03',
    scope: 'brand-mthds-pipelex-method--claude-4-8-opus',
    manifest: {
      name: 'MTHDS',
      website: 'https://mthds.ai/',
      logo: {
        onLight: 'https://mthds.ai/latest/images/mthds-black_on_transparent.png',
        onDark: 'https://mthds.ai/latest/images/mthds-white_on_transparent.png',
      },
      webfont: {
        provider: 'google-fonts',
        family: 'Roboto',
      },
    },
  },
  {
    brand: 'pipelex',
    producerId: 'claude-code-session--claude-fable-5-1',
    producer: 'claude-code-session',
    model: 'claude-fable-5-1',
    date: '2026-09-03',
    scope: 'brand-pipelex-claude-code-session--claude-fable-5-1',
    manifest: {
      name: 'Pipelex',
      website: 'https://pipelex.com/',
      logo: {
        onLight: 'https://d2cinlfp2qnig1.cloudfront.net/logo/Pipelex-logo-bot-1119x352.png',
        onDark: 'https://d2cinlfp2qnig1.cloudfront.net/logo/Pipelex-logo-wot-1119x352.png',
      },
      webfont: {
        provider: 'google-fonts',
        family: 'Inter',
      },
    },
  },
  {
    brand: 'pipelex',
    producerId: 'pipelex-method--claude-4.8-opus',
    producer: 'pipelex-method',
    model: 'claude-4.8-opus',
    date: '2026-09-03',
    scope: 'brand-pipelex-pipelex-method--claude-4-8-opus',
    manifest: {
      name: 'Pipelex',
      website: 'https://pipelex.com/',
      logo: {
        onLight: 'https://d2cinlfp2qnig1.cloudfront.net/logo/Pipelex-logo-bot-1119x352.png',
        onDark: 'https://pipelex.com/logo.png',
      },
      webfont: {
        provider: 'google-fonts',
        family: 'Inter',
      },
    },
  },
];
