import { existsSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { type AssembledBrand, assembleBrand } from '../../brand';

/**
 * The story brands, built from the corpus: what `make brands` writes and what
 * the corpus guard (`__tests__/brands.test.ts`) rebuilds to check it.
 *
 * The corpus is `data/brands/<brand>/<producer>/`, three JSON files each, as a
 * producer wrote them. Every one is validated and compiled by the brand
 * entry's own `assembleBrand`, and the build writes, under
 * `src/__stories__/generative/brands/`, one stylesheet per brand, an
 * `index.css` importing them all, and `generated.ts` naming each with its
 * provenance and its manifest. The outputs are committed, so the Storybook
 * needs nothing but node, and none of it is in an entry tree.
 *
 * Node-only: nothing a story imports reaches this module.
 */

export const BRANDS_DIR = 'data/brands';
export const OUT_DIR = 'src/__stories__/generative/brands';
const FILES = ['brand.json', 'tokens.json', 'provenance.json'] as const;

export interface BrandDir {
  brand: string;
  producerId: string;
  dir: string;
}

function isDirectory(entry: { isDirectory(): boolean; name: string }) {
  return entry.isDirectory() && !entry.name.startsWith('.');
}

/** Every `<brand>/<producer>/` directory of the corpus, sorted. */
export function brandDirs(repo: string): BrandDir[] {
  const root = path.join(repo, BRANDS_DIR);
  if (!existsSync(root)) return [];
  const dirs: BrandDir[] = [];
  for (const brand of readdirSync(root, { withFileTypes: true }).filter(isDirectory)) {
    const brandDir = path.join(root, brand.name);
    for (const producer of readdirSync(brandDir, { withFileTypes: true }).filter(isDirectory)) {
      dirs.push({
        brand: brand.name,
        producerId: producer.name,
        dir: path.join(brandDir, producer.name),
      });
    }
  }
  return dirs.sort((a, b) => keyOf(a).localeCompare(keyOf(b)));
}

export function keyOf(entry: { brand: string; producerId: string }): string {
  return `${entry.brand}/${entry.producerId}`;
}

export type CorpusBuild =
  | { ok: true; brands: AssembledBrand[] }
  | { ok: false; failures: { key: string; problems: string[] }[] };

/** The whole corpus, or every brand that did not validate with its problems. All or nothing. */
export function buildCorpus(repo: string): CorpusBuild {
  const brands: AssembledBrand[] = [];
  const failures: { key: string; problems: string[] }[] = [];
  for (const entry of brandDirs(repo)) {
    const missing = FILES.filter((file) => !existsSync(path.join(entry.dir, file)));
    if (missing.length > 0) {
      failures.push({ key: keyOf(entry), problems: [`missing ${missing.join(', ')}`] });
      continue;
    }
    const read = (file: string): unknown => {
      try {
        return JSON.parse(readFileSync(path.join(entry.dir, file), 'utf8'));
      } catch (error) {
        return { notJson: error instanceof Error ? error.message : String(error) };
      }
    };
    const result = assembleBrand({
      brand: entry.brand,
      producerId: entry.producerId,
      manifest: read('brand.json'),
      tokens: read('tokens.json'),
      provenance: read('provenance.json'),
    });
    if (result.ok) brands.push(result.brand);
    else failures.push({ key: keyOf(entry), problems: result.problems });
  }
  return failures.length > 0 ? { ok: false, failures } : { ok: true, brands };
}

/** The stylesheet a brand is written to, under `OUT_DIR`. */
export function stylesheetFile(brand: Pick<AssembledBrand, 'brand' | 'producerId'>): string {
  return `${brand.brand}--${brand.producerId}.css`;
}

/** The stylesheet's content: where it came from, then what `compileBrand` wrote. */
export function stylesheetText(brand: AssembledBrand): string {
  return [
    `/* Generated by \`make brands\` from ${BRANDS_DIR}/${brand.brand}/${brand.producerId}/ - DO NOT EDIT.`,
    ' * A story fixture: outside every entry tree, shipped in nothing. */',
    brand.css,
  ].join('\n');
}

export function indexCssText(brands: readonly AssembledBrand[]): string {
  return [
    '/* Generated by `make brands` - DO NOT EDIT. Every story brand, for a story to load in one import. */',
    ...brands.map((brand) => `@import './${stylesheetFile(brand)}';`),
    '',
  ].join('\n');
}

/** What a story needs to name a brand and paint in it; the tokens stay in the stylesheet. */
export function generatedModuleText(brands: readonly AssembledBrand[]): string {
  const entries = brands.map((brand) => ({
    brand: brand.brand,
    producerId: brand.producerId,
    producer: brand.producer,
    model: brand.model,
    date: brand.date,
    scope: brand.scope,
    manifest: brand.manifest,
  }));
  return [
    `// Generated by \`make brands\` from ${BRANDS_DIR}/ - DO NOT EDIT.`,
    '// One entry per producer directory: who made the brand, the class its',
    '// stylesheet is scoped to, and the manifest the app bar reads.',
    '',
    "import type { BrandManifest, BrandProducer } from '../../../brand';",
    '',
    'export interface BrandBuild {',
    '  brand: string;',
    '  producerId: string;',
    '  producer: BrandProducer;',
    '  model: string;',
    '  date: string;',
    '  scope: string;',
    '  manifest: BrandManifest;',
    '}',
    '',
    `export const BRAND_BUILDS: readonly BrandBuild[] = ${JSON.stringify(entries, null, 2)};`,
    '',
  ].join('\n');
}
