import type { Spec } from '@json-render/core';

/**
 * A spec with its provenance - the shape both the captured and the authored
 * fixtures take, so a story renders either without knowing which it holds.
 *
 * A spec is a payload's twin: the one artifact no projection can produce. So
 * it follows the payload's rules - generated by a pass, committed with its
 * provenance - plus the two facts a spec needs and a payload does not: the
 * MODEL (or author) that produced it, and the HASH of the catalog prompt it
 * was produced against, so a catalog change that invalidates it is visible.
 */
export interface SpecFixture {
  /** `results.nested_result`. */
  pipeRef: string;
  /** Who produced it: the designer method, or a person writing from the brief. */
  source: 'generated' | 'authored';
  /** The model id the designer method ran with. Generated only. */
  model?: string;
  /** Who wrote it. Authored only. */
  author?: string;
  /** The first twelve hex digits of the SHA-256 of the catalog prompt at the time. */
  promptHash: string;
  /** The day it was produced, `YYYY-MM-DD`. */
  date: string;
  /** The brief it was produced from, repo-relative. */
  brief: string;
  /** The JSONL patch lines, exactly as emitted (generated) or as `specToJsonl` renders them (authored). */
  jsonl: string;
  /** The compiled spec. */
  spec: Spec;
}
