#!/usr/bin/env node
/**
 * Build the brands: `data/brands/<brand>/<producer>/` in, the scoped
 * stylesheets and the fixture module a brand story loads out.
 *
 * A brand is data a producer wrote - three JSON files, validated here against
 * the brand contract (`src/__stories__/generative/brand/`) and compiled through
 * Terrazzo into `src/__stories__/_generated/brands/`: one `.css` per brand
 * and producer, an `index.css` importing each, and `brands.ts` carrying every
 * brand with its provenance, its tokens and its stylesheet. The outputs are
 * committed, so the Storybook needs nothing but node; the node test
 * `src/__stories__/__tests__/brands.test.ts` rebuilds each brand from its data
 * and fails on a committed stylesheet that is not what the data produces.
 *
 * All or nothing: one brand that does not validate writes nothing, and its
 * problems are printed in the words the contract uses - the same list a
 * producer's repair round is handed.
 *
 * Imports TypeScript straight from `src/`, which node cannot resolve on its own
 * (the imports are extensionless), so the Makefile runs this under tsx.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BRANDS_DIR = path.join(REPO, 'data/brands');
const OUT_DIR = path.join(REPO, 'src/__stories__/_generated/brands');
const FILES = ['brand.json', 'tokens.json', 'provenance.json'];

function die(message) {
  process.stderr.write(`build-brands: ${message}\n`);
  process.exit(1);
}

function isDirectory(entry) {
  return entry.isDirectory() && !entry.name.startsWith('.');
}

/** Every `<brand>/<producer>/` directory carrying the three files. */
function discover() {
  if (!existsSync(BRANDS_DIR)) return [];
  const sources = [];
  for (const brand of readdirSync(BRANDS_DIR, { withFileTypes: true }).filter(isDirectory)) {
    const brandDir = path.join(BRANDS_DIR, brand.name);
    for (const producer of readdirSync(brandDir, { withFileTypes: true }).filter(isDirectory)) {
      const dir = path.join(brandDir, producer.name);
      const missing = FILES.filter((file) => !existsSync(path.join(dir, file)));
      if (missing.length > 0) {
        die(`${brand.name}/${producer.name}: missing ${missing.join(', ')}`);
      }
      sources.push({ brand: brand.name, producerId: producer.name, dir });
    }
  }
  return sources.sort((a, b) =>
    `${a.brand}/${a.producerId}`.localeCompare(`${b.brand}/${b.producerId}`),
  );
}

function readJson(dir, file) {
  const text = readFileSync(path.join(dir, file), 'utf8');
  try {
    return JSON.parse(text);
  } catch (error) {
    die(`${path.relative(REPO, path.join(dir, file))}: not JSON - ${error.message}`);
  }
}

function emitModule(fixtures) {
  return [
    '// Generated by `make brands` from data/brands/ - DO NOT EDIT.',
    '// Each entry is one producer directory: its provenance, its manifest, its',
    '// tokens as validated, and the stylesheet Terrazzo compiled from them.',
    '',
    "import type { BrandFixture } from '../../generative/brand/brand-fixture';",
    '',
    `export const BRANDS: BrandFixture[] = ${JSON.stringify(fixtures, null, 2)};`,
    '',
  ].join('\n');
}

async function main() {
  const [
    { assembleBrand },
    { brandCssFilename, brandStylesheet },
    { renderBrandContract },
    { promptHashOf },
  ] = await Promise.all([
    import('../src/__stories__/generative/brand/pipeline.ts'),
    import('../src/__stories__/generative/brand/brand-fixture.ts'),
    import('../src/__stories__/generative/brand/contract.ts'),
    import('../src/__stories__/generative/prompt-hash.ts'),
  ]);
  const contractHash = promptHashOf(renderBrandContract());
  const sources = discover();
  if (sources.length === 0) {
    process.stdout.write('build-brands: no brands under data/brands/, nothing to do.\n');
    return;
  }

  const fixtures = [];
  let failed = false;
  for (const source of sources) {
    const label = `${source.brand}/${source.producerId}`;
    const result = await assembleBrand({
      brand: source.brand,
      producerId: source.producerId,
      manifest: readJson(source.dir, 'brand.json'),
      tokens: readJson(source.dir, 'tokens.json'),
      provenance: readJson(source.dir, 'provenance.json'),
      contractHash,
    });
    for (const warning of result.warnings)
      process.stdout.write(`  ${label}: warning: ${warning}\n`);
    if (!result.ok) {
      failed = true;
      process.stderr.write(`  ${label}: ${result.problems.length} problem(s)\n`);
      for (const problem of result.problems) process.stderr.write(`    - ${problem}\n`);
      continue;
    }
    fixtures.push(result.fixture);
    process.stdout.write(`  ${label}: ok (scope .${result.fixture.scope})\n`);
  }
  if (failed) die('a brand did not validate; nothing was written.');

  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });
  const filenames = [];
  for (const fixture of fixtures) {
    const filename = brandCssFilename(fixture.brand, fixture.producerId);
    writeFileSync(path.join(OUT_DIR, filename), brandStylesheet(fixture));
    filenames.push(filename);
  }
  writeFileSync(
    path.join(OUT_DIR, 'index.css'),
    [
      '/* Generated by `make brands` - DO NOT EDIT. Every brand stylesheet, for a story to load in one import. */',
      ...filenames.map((filename) => `@import './${filename}';`),
      '',
    ].join('\n'),
  );
  const modulePath = path.join(OUT_DIR, 'brands.ts');
  writeFileSync(modulePath, emitModule(fixtures));
  // Formatted like every committed file, so `make check` reads the tree as a
  // whole; the node test formats its expectation the same way.
  execFileSync(
    'npx',
    ['prettier', '--write', modulePath, ...filenames.map((f) => path.join(OUT_DIR, f))],
    {
      stdio: 'ignore',
      cwd: REPO,
    },
  );
  process.stdout.write(
    `build-brands: ${fixtures.length} brand build(s) -> ${path.relative(REPO, OUT_DIR)}/ (contract ${contractHash})\n`,
  );
}

main().catch((error) => die(error?.stack ?? String(error)));
