import { z } from 'zod';
import { fixtureId, type Producer } from '../spec-fixture';
import type { BrandManifest } from './manifest';
import type { BrandTokens } from './tokens-schema';

/**
 * A brand with its provenance - what the build writes for each directory
 * under `data/brands/`, and what a brand story renders from.
 *
 * A brand follows the spec's rules exactly: produced by a pass, committed
 * with its provenance, titled by what made it and by nothing else. The record
 * is the spec fixture's, with what a brand has and a spec does not - the
 * manifest, the tokens, the stylesheet the build wrote and the class that
 * scopes it - and without the JSONL, because a token file is its own wire
 * form. The `producerId` is the directory the data lives in, and it must be
 * what `fixtureId` computes from the provenance, so the tree and the record
 * cannot disagree about who made a brand.
 */

export const PRODUCERS = ['pipelex-method', 'claude-code-subagent', 'claude-code-session'] as const;

/** `provenance.json`, as a producer writes it. */
export const brandProvenanceSchema = z.strictObject({
  producer: z.enum(PRODUCERS),
  /** The model id: the one the method ran with, or the Claude Code model behind the session. */
  model: z.string().min(1),
  /** The day it was produced, `YYYY-MM-DD`. */
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  /** The contract brief it was produced from, repo-relative. */
  brief: z.string().min(1),
  /** The first twelve hex digits of the SHA-256 of the contract brief at the time. */
  contractHash: z.string().regex(/^[0-9a-f]{12}$/, 'twelve hex digits'),
  /** The creative seed handed over with the brief, verbatim, when one was. */
  seed: z.string().min(1).optional(),
  /** Where the site facts came from: a file, or a sentence for a brand read by hand. */
  siteFacts: z.string().min(1).optional(),
  /** How many repair rounds the producer ran before the file validated. */
  rounds: z.number().int().min(0).optional(),
});

export type BrandProvenance = z.infer<typeof brandProvenanceSchema>;

export interface BrandFixture extends BrandProvenance {
  /** The brand's directory name under `data/brands/`: `pipelex`. */
  brand: string;
  /** The producer's directory name under the brand: `claude-code-session--claude-fable-5-1`. */
  producerId: string;
  manifest: BrandManifest;
  tokens: BrandTokens;
  /** The class the page root carries; the stylesheet is scoped to it. */
  scope: string;
  /** The stylesheet the build wrote, as committed under `_generated/brands/`. */
  css: string;
  /** What Terrazzo's lint said and the build let pass - a duplicate value, typically. */
  warnings: string[];
}

/** The id a brand's directory and story are keyed by: `producer--model[--seeded]`. */
export function brandProducerId(provenance: Pick<BrandProvenance, 'producer' | 'model' | 'seed'>) {
  return fixtureId({
    producer: provenance.producer as Producer,
    model: provenance.model,
    seed: provenance.seed,
  });
}

/**
 * The scope class: `brand-<brand>-<producerId>`, with every character outside
 * `[a-z0-9-]` replaced - a model id carries dots, and a dot ends a class
 * selector.
 */
export function brandScope(brand: string, producerId: string): string {
  return `brand-${brand}-${producerId}`.toLowerCase().replace(/[^a-z0-9-]/g, '-');
}

/** The file the build writes for one brand, under `_generated/brands/`. */
export function brandCssFilename(brand: string, producerId: string): string {
  return `${brand}--${producerId}.css`;
}

/** The file's content: a line naming the source, then what Terrazzo emitted. */
export function brandStylesheet(
  fixture: Pick<BrandFixture, 'brand' | 'producerId' | 'css'>,
): string {
  return `/* Generated by \`make brands\` from data/brands/${fixture.brand}/${fixture.producerId}/tokens.json - DO NOT EDIT. */\n${fixture.css}`;
}
